version: "3.8"

services:
  node1:
    image: kommander:latest   
    container_name: node1
    environment:
      - PEER_HOST=172.20.0.2
      - PEER_PORT=8081
      - ASPNETCORE_URLS=http://*:8081;http://*:8004
    ports:
      - "8081:8004"
    volumes:
      - node1-data:/app/data  
    networks:
      custom_net:
        ipv4_address: 172.20.0.2

  node2:
    image: kommander:latest
    container_name: node2
    environment:
      - PEER_HOST=node2
      - PEER_PORT=8082
      - ASPNETCORE_URLS=http://*:8082;http://*:8004
    ports:
      - "8082:8004"
    volumes:
      - node2-data:/app/data    
    networks:
      custom_net:
        ipv4_address: 172.20.0.3

  node3:
    image: kommander:latest
    container_name: node3
    environment:
      - PEER_HOST=node3
      - PEER_PORT=8083
      - ASPNETCORE_URLS=http://*:8083;http://*:8004
    ports:
      - "8083:8004"
    volumes:
      - node3-data:/app/data        
    networks:
      custom_net:
        ipv4_address: 172.20.0.4

volumes:
  node1-data:
  node2-data:
  node3-data:          

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
